### ISSUE TITLE
Shopkeeper Skin Bug

### ISSUE THREAD

**Issue by mingasdf** [IamTheDefender/BedWars1058-Cosmetics-Free#11]
When game start,if the Shopkeeper skin is a npc, it will not spawn team upgrades npc 
![2023-06-14_21 38 07](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/assets/124030832/81890439-8eeb-423d-a591-4f3eb6bcb317)
,the shop npc will load,if Shopkeeper Skin is not npc(mobs,villager) will all not spawn
![2023-06-14_21 59 02](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/assets/124030832/1fb5ccc6-ac23-4c89-8305-0af0724dfb18),
it start with this error:

[22:06:48 WARN]: [BW1058-Cosmetics] Task #188304 for BW1058-Cosmetics v1.4.2 generated an exception
java.lang.NoClassDefFoundError: net/citizensnpcs/api/npc/NPC$Metadata
        at me.defender.cosmetics.api.category.shopkeeperskins.utils.ShopKeeperSkinsUtils.createEntityNPC(ShopKeeperSkinsUtils.java:39) ~[?:?]
        at me.defender.cosmetics.api.category.shopkeeperskins.utils.ShopKeeperSkinsUtils.spawnShopKeeperNPC(ShopKeeperSkinsUtils.java:160) ~[?:?]
        at me.defender.cosmetics.api.category.shopkeeperskins.items.ShopKeeperItems$1.execute(ShopKeeperItems.java:80) ~[?:?]
        at me.defender.cosmetics.api.category.shopkeeperskins.ShopKeeperHandler$1.run(ShopKeeperHandler.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.npc.NPC$Metadata
        ... 11 more

**Comment by IamTheDefender** [comment]
Downloaded the latest version of Citizens from jenkins

**Comment by IamTheDefender** [comment]
I will look into the bug

**Comment by IamTheDefender** [comment]
I forgot to mention but could you try the 1.4.4 update/

**Comment by IamTheDefender** [comment]
I guess you might be inactive but if you are not and the plugin does not work you can reopen the issue. I will look into it further.
