### ISSUE TITLE
An Error

### ISSUE THREAD

**Issue by banwang123** [IamTheDefender/BedWars1058-Cosmetics-Free#18]
Hello Here is the Error in console:
[17:23:04 ERROR]: Could not pass event PlayerJoinEvent to BW1058-Cosmetics v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:47) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:45) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
It may cause the server no response for many seconds.

**Comment by IamTheDefender** [comment]
Hello! Sorry for not replying sooner, try this version

https://cdn.discordapp.com/attachments/1000414879674548285/1149710532543250542/BW1058-Cosmetics-1.4.5.jar

**Comment by banwang123** [comment]
[23:16:49 ERROR]: Could not pass event PlayerJoinEvent to BW1058-Cosmetics v1.4.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:47) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:45) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
Sorry, it wasn't successfully fixed. I checked the MySQL. Other plugins can connect the MySQL normally

**Comment by IamTheDefender** [comment]
I am pretty sure it's not to do with the plugin because I have checked and it does not have any issues with connection, if the issue persist send the latest logs

**Comment by banwang123** [comment]
[12:36:46 INFO]: banwang[/27.15.39.17:53040] logged in with entity id 40785 at ([build]85.86687729239947, 231.5, 27.410439264657686)
[12:36:46 INFO]: [Vulcan] banwang 正使用 Fml,forge 进入服务器!
[12:36:51 INFO]: banwang lost connection: Disconnected
[12:37:06 INFO]: UUID of player banwang is 05a5b7ab-3dd0-3d23-9edc-f011435381ab
[12:37:07 ERROR]: Failed to load player-data: Connection is closed
[12:37:07 WARN]: java.sql.SQLException: Connection is closed
[12:37:07 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
[12:37:07 WARN]:        at com.sun.proxy.$Proxy44.prepareStatement(Unknown Source)
[12:37:07 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[12:37:07 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[12:37:07 WARN]:        at me.defender.cosmetics.database.PlayerData.createData(PlayerData.java:67)
[12:37:07 WARN]:        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:51)
[12:37:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:37:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:37:07 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:37:07 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[12:37:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[12:37:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:37:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:37:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710)
[12:37:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
[12:37:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[12:37:07 INFO]: banwang[/27.15.39.17:53377] logged in with entity id 41829 at ([build]85.86687729239947, 231.5, 27.410439264657686)
[12:37:07 INFO]: [Vulcan] banwang 正使用 Fml,forge 进入服务器!
[12:37:13 INFO]: banwang lost connection: Disconnected
[12:37:19 INFO]: UUID of player banwang is 05a5b7ab-3dd0-3d23-9edc-f011435381ab
[12:37:19 ERROR]: Failed to load player-data: Connection is closed
[12:37:19 WARN]: java.sql.SQLException: Connection is closed
[12:37:19 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
[12:37:19 WARN]:        at com.sun.proxy.$Proxy44.prepareStatement(Unknown Source)
[12:37:19 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[12:37:19 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[12:37:19 WARN]:        at me.defender.cosmetics.database.PlayerData.createData(PlayerData.java:67)
[12:37:19 WARN]:        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:51)
[12:37:19 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:37:19 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:37:19 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:37:19 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[12:37:19 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[12:37:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:37:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:37:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710)
[12:37:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
[12:37:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[12:37:19 INFO]: banwang[/27.15.39.17:53537] logged in with entity id 43299 at ([build]85.86687729239947, 231.5, 27.410439264657686)
[12:37:19 INFO]: [Vulcan] banwang 正使用 Fml,forge 进入服务器!
[13:06:24 WARN]: [SkinsRestorer] Failed to get release info from api.github.com.
 If this message is repeated a lot, please see http://skinsrestorer.net/firewall
[13:19:03 INFO]: UUID of player banwang1 is 28419d3e-29e3-352d-aafc-e36aad40545b
[13:19:03 ERROR]: Failed to load player-data: Connection is closed
[13:19:03 WARN]: java.sql.SQLException: Connection is closed
[13:19:03 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:502)
[13:19:03 WARN]:        at com.sun.proxy.$Proxy44.prepareStatement(Unknown Source)
[13:19:03 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[13:19:03 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[13:19:03 WARN]:        at me.defender.cosmetics.database.PlayerData.createData(PlayerData.java:67)
[13:19:03 WARN]:        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:51)
[13:19:03 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:19:03 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:19:03 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:19:03 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:19:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:19:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:19:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:19:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710)
[13:19:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
[13:19:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:19:33 ERROR]: Could not pass event PlayerJoinEvent to BW1058-Cosmetics v1.4.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:871) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:47) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at me.defender.cosmetics.database.PlayerOwnedData.<init>(PlayerOwnedData.java:45) ~[?:?]
        at me.defender.cosmetics.listener.PlayerJoinListener.onJoin(PlayerJoinListener.java:54) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
        ... 14 more
Is it need BedWars-Proxy Plugin? When a player join the server.The console will throw: Connection is closed.

**Comment by IamTheDefender** [comment]
Can I get the full logs?

**Comment by banwang123** [comment]
here is the logs of Lobby :
[latest.log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/12699699/latest.log)
 here is logs of BedWars Game :

[latest.log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/12699743/latest.log)

**Comment by IamTheDefender** [comment]
Bug fixes in [pull request](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/pull/22) please wait for release of patch publicly.
