### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HanielCota** [IamTheDefender/BedWars1058-Cosmetics-Free#42]
[23:03:26 WARN]: java.lang.IllegalArgumentException: name cannot be null
[23:03:26 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[23:03:26 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.getWorld(CraftServer.java:1470)
[23:03:26 WARN]:        at org.bukkit.Bukkit.getWorld(Bukkit.java:874)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.util.StartupUtils.getCosmeticLocation(StartupUtils.java:296)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.category.shopkeeperskins.preview.ShopKeeperPreview.sendPreviewShopKeeperSkin(ShopKeeperPreview.java:72)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.menu.CategoryMenu.previewClick(CategoryMenu.java:348)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.menu.CategoryMenu.lambda$onOpen$0(CategoryMenu.java:122)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.support.hcore.ui.inventory.listeners.InventoryClickListener.lambda$onClick$1(InventoryClickListener.java:53)
[23:03:26 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.support.hcore.ui.inventory.listeners.InventoryClickListener.lambda$onClick$2(InventoryClickListener.java:51)
[23:03:26 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[23:03:26 WARN]:        at BedWars-Cosmetics-1.4.6.jar//me.defender.cosmetics.support.hcore.ui.inventory.listeners.InventoryClickListener.onClick(InventoryClickListener.java:35)
[23:03:26 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor218.execute(Unknown Source)
[23:03:26 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:03:26 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[23:03:26 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:03:26 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[23:03:26 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[23:03:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[23:03:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3106)
[23:03:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[23:03:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[23:03:26 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[23:03:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:03:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:03:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[23:03:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[23:03:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1333)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1222)
[23:03:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:03:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by IamTheDefender** [comment]
Please set the player preview and cosmetic preview locations via the commands (try the tab auto complete for /bwc setup.....)
