### ISSUE TITLE
 Error occurred while enabling Cosmetics v1.4.6 (Is it up to date?)

### ISSUE THREAD

**Issue by HanielCota** [IamTheDefender/BedWars1058-Cosmetics-Free#43]
[23:09:28 ERROR]: Error occurred while enabling Cosmetics v1.4.6 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant me.defender.cosmetics.api.cosmetics.RarityType.COMUM
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at me.defender.cosmetics.api.cosmetics.RarityType.valueOf(RarityType.java:5) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at me.defender.cosmetics.category.killmessage.items.KillMessageItems$1.getRarity(KillMessageItems.java:62) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at me.defender.cosmetics.api.cosmetics.category.KillMessage.register(KillMessage.java:39) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at me.defender.cosmetics.category.killmessage.items.KillMessageItems.registerConfigItems(KillMessageItems.java:65) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at me.defender.cosmetics.util.StartupUtils.loadCosmetics(StartupUtils.java:248) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at me.defender.cosmetics.Cosmetics.onEnable(Cosmetics.java:141) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-446]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-446]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-446]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-446]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by IamTheDefender** [comment]
I would need your KillMessages.yml

**Comment by IamTheDefender** [comment]
OP Inactive
