### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by HanielCota** [IamTheDefender/BedWars1058-Cosmetics-Free#45]
[12:30:27 ERROR]: Could not pass event InventoryOpenEvent to Cosmetics v1.4.6
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at me.defender.cosmetics.category.woodskin.WoodSkinHandler1058.onShopOpen(WoodSkinHandler1058.java:59) ~[BedWars-Cosmetics-1.4.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor433.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-15679]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1480) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1459) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:361) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:345) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at com.andrei1058.bedwars.shop.main.ShopIndex.open(ShopIndex.java:103) ~[bedwars-plugin-23.12.2.jar:?]
        at com.andrei1058.bedwars.shop.listeners.ShopOpenListener.onShopOpen(ShopOpenListener.java:47) ~[bedwars-plugin-23.12.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-15679]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[slimeworldmanager-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2722) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2775) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:161) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1473) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1450) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1373) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1351) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15679]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by IamTheDefender** [comment]
The bug is fixed in the v1.4.7, join the discord server for dev builds
