### ISSUE TITLE
Issue with Sprays

### ISSUE THREAD

**Issue by TrixterPro** [IamTheDefender/BedWars1058-Cosmetics-Free#52]
## Error:
```bash
[09:36:21 WARN]: javax.imageio.IIOException: Can't read input file!
[09:36:21 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1310)
[09:36:21 WARN]:        at xyz.iamthedefender.cosmetics.category.sprays.util.CustomRenderer.load(CustomRenderer.java:51)
[09:36:21 WARN]:        at xyz.iamthedefender.cosmetics.category.sprays.util.SpraysUtil.lambda$spawnSprays$0(SpraysUtil.java:82)
[09:36:21 WARN]:        at com.hakan.core.scheduler.Scheduler.lambda$run$0(Scheduler.java:269)
[09:36:21 WARN]:        at com.hakan.core.scheduler.Scheduler.lambda$run$1(Scheduler.java:281)
[09:36:21 WARN]:        at com.hakan.core.scheduler.Scheduler.lambda$run$2(Scheduler.java:309)
[09:36:21 WARN]:        at com.hakan.core.scheduler.SchedulerRunnable.run(SchedulerRunnable.java:152)
[09:36:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[09:36:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[09:36:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[09:36:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[09:36:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[09:36:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[09:36:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[09:36:21 ERROR]: Could not load the File for the server-logo. Check if the File in Sprays.yml is valid: plugins/BedWars1058/Addons/Cosmetics/Sprays/server-logo
```

## reproducing this error:
- go to plugins>BedWars1058>Addons>Cosmetics>Categories>Sprays.yml
- edit the first item (server-logo) like this
```yml
server-logo:
    item: BARRIER:0
    file: server-icon.png
    rarity: NONE
    price: 0
```
- place the server-icon.png in plugins>BedWars1058>Addons>Cosmetics>Sprays
- Restart the server
if you now try to use/preview any spray, it will show only server-icon.png as the spray

then, to get that error:
- just reset the Sprays.yml file to the default one,
- change first item (server-logo) to default:
```yml
server-logo:
    item: BARRIER:0
    file: server-icon.png
    rarity: NONE
    price: 0
```
- remove the server-icon.png from the Sprays directory
- now if you try to preview/user any spray, it should give you that error

**Comment by IamTheDefender** [comment]
Fixed in v1.4.8
