### ISSUE TITLE
ender drageon cant fly

### ISSUE THREAD

**Issue by fwwwwwwwwww** [IamTheDefender/BedWars1058-Cosmetics-Free#54]
**error code:**

```
[07:24:52 WARN]: [BedWars-Cosmetics] Task #103277 for Cosmetics v1.4.7 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftEnderDragon cannot be cast to class org.bukkit.entity.Creature (org.bukkit.craftbukkit.v1_20_R1.entity.CraftEnderDragon and org.bukkit.entity.Creature are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
        at xyz.iamthedefender.cosmetics.category.victorydance.items.DragonRiderDance$1.run(DragonRiderDance.java:85) ~[BedWars-Cosmetics-v1.4.7 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
        
 **Plugins Version**
 
 bwc:last
 vault:last
 worldedit:  FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-952
 protocolib:5.30
 papi:2.11.6
 citizens:2.0.32 b3149
 bw1058:last

**Comment by IamTheDefender** [comment]
Are you in the support discord server?

**Comment by fwwwwwwwwww** [comment]
emm ye but i not have 2FA

**Comment by fwwwwwwwwww** [comment]
sry for let you wait

**Comment by IamTheDefender** [comment]
Oh okay... I will send you an update here soon

**Comment by fwwwwwwwwww** [comment]
thx

**Comment by IamTheDefender** [comment]
Update is available to download https://github.com/IamTheDefender/Bedwars-Cosmetics/releases/tag/1.4.8
