### ISSUE TITLE
Can't load the plugin!

### ISSUE THREAD

**Issue by Nerd10000** [IamTheDefender/BedWars1058-Cosmetics-Free#55]
Hello I got this error when I start the server.
 [20:52:52 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins/BedWars-Cosmetics-v1.4.7(1).jar' failed to update!
java.lang.RuntimeException: Directory 'plugins/BedWars-Cosmetics-v1.4.7(1).jar' failed to update!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:57) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:64) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.util.zip.ZipException: zip file is empty
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:120) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	... 21 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1781) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1562) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1495) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1458) ~[?:?]
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:282) ~[?:?]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:126) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:101) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:55) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	... 21 more

**Comment by IamTheDefender** [comment]
Can you make sure that you uploaded the plugin correctly? ("Caused by: java.util.zip.ZipException: zip file is empty")
